on: [push, pull_request]

name: CI

jobs:
  test:
    name: Tests
    runs-on: ${{ matrix.target }}
    strategy:
      matrix:
        rust:
          - stable
          - 1.56
        target:
          - ubuntu-latest
          - windows-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install toolchain
        run: rustup toolchain add ${{ matrix.rust }}

      - name: cargo test
        run: cargo +${{ matrix.rust }} test

  check:
    name: Check wasi
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - 1.56
          - stable

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install toolchain
        run: rustup toolchain add ${{ matrix.rust }} && rustup +${{ matrix.rust }} target add wasm32-wasi

      - name: cargo check
        run: cargo +${{ matrix.rust }} check --target wasm32-wasi
