on: [push, pull_request]

name: CI

jobs:
  test:
    name: Tests
    runs-on: ${{ matrix.target }}
    strategy:
      matrix:
        rust:
          - stable
          - 1.85
        target:
          - ubuntu-latest
          - windows-latest

    steps:
      - uses: actions/checkout@v4

      - run: rustup toolchain add ${{ matrix.rust }}

      - run: cargo +${{ matrix.rust }} test

  check:
    name: Check wasi
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - 1.85
          - stable

    steps:
      - uses: actions/checkout@v4

      - run: rustup toolchain add ${{ matrix.rust }} && rustup default ${{ matrix.rust }}
      - run: rustup target add wasm32-wasip1

      - run: cargo check --target wasm32-wasip1
